.IX Title "pdf2img 1"
.TH pdf2img 1 "2017-10-06" "1.7" ""
.if n .ad l
.nh
.SH "NAME"
pdf2img \- Convert PDF books to PNG, JPG and other image formats easily.
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
pdf2img is a small and open source graphical application written in C and designed to act as a quick solution for converting \s-1PDF\s0 books to image files.
.PP
pdf2img features support for four different image formats, including \s-1PNG, JPG, BMP,\s0 and \s-1TIFF,\s0 as well as support for ten Ghostscript devices, including png16m, pngalpha, pnggray, jpeg, jpegcmyk, jpeggray, bmp16m, bmpgray, tiff24nc, and tiffgray.
.PP
The program can convert multiple pages at once, into multiple images, with a single mouse click.
.SH "BUGS"
.IX Header "BUGS"
Bugs can be filed at:
.PP
https://github.com/boji/pdf2img\-c
.SH "AUTHORS"
.IX Header "AUTHORS"
\&\fBpdf2img\fR is released under the \s-1GNU\s0 General Public License, version 3.
